[package]
name = "slackbot-rust"
version = "0.1.0"
authors = ["papamitra <papamitra@gmail.com>"]

[dependencies]
mio = "0.6"
hyper = "0.10"
curl = "0.4.6"
hyper-native-tls = "*"
serde_json = "1.0"
futures = "0.1"
tokio-core = "0.1"
websocket = "0.20"
